### ISSUE TITLE
Experience an error in add a OrderShipmentComment

### ISSUE THREAD

**Issue by alex-fernandez** [mulesoft/magento-connector#34]
It seems that the there is an issue on SOAP and Axis conversion of Magento operation output. I was unable to get rid of the exception error. Are there any solution on this, I already tried recompiling the connector but the issue still persist.

org.mule.module.magento.MagentoCloudConnector: An exception was thrown while invoking addOrderShipmentComment: org.xml.sax.SAXException: Bad types (boolean -> int)
ERROR 2015-04-23 14:24:53,583 [ActiveMQ Session Task-2] org.mule.retry.notifiers.ConnectNotifier: Failed to connect/reconnect: Work Descriptor. Root Exception was: Bad types (boolean -> int). Type: class org.xml.sax.SAXException
org.mule.exception.CatchMessagingExceptionStrategy: 
********************************************************************************
Message               : Failed to invoke addOrderShipmentComment. Message payload is of type: String
Code                  : MULE_ERROR--2
--------------------------------------------------------------------------------
Exception stack is:
1. Bad types (boolean -> int) (org.xml.sax.SAXException)
  org.apache.axis.message.RPCHandler:286 (null)
2. ; nested exception is: 
	org.xml.sax.SAXException: Bad types (boolean -> int) (org.apache.axis.AxisFault)
  org.apache.axis.AxisFault:101 (null)
3. org.xml.sax.SAXException: Bad types (boolean -> int) (org.mule.module.magento.api.MagentoException)
  org.mule.module.magento.api.MagentoClientAdaptor:87 (http://www.mulesoft.org/docs/site/current3/apidocs/org/mule/module/magento/api/MagentoException.html)
4. Failed to invoke addOrderShipmentComment. Message payload is of type: String (org.mule.api.MessagingException)
  org.mule.module.magento.processors.AddOrderShipmentCommentMessageProcessor:173 (http://www.mulesoft.org/docs/site/current3/apidocs/org/mule/api/MessagingException.html)
--------------------------------------------------------------------------------
Root Exception stack trace:
org.xml.sax.SAXException: Bad types (boolean -> int)
	at org.apache.axis.message.RPCHandler.onStartChild(RPCHandler.java:286)
	at org.apache.axis.encoding.DeserializationContext.startElement(DeserializationContext.java:1035)
	at org.apache.axis.message.SAX2EventRecorder.replay(SAX2EventRecorder.java:165)
    + 3 more (set debug level logging or '-Dmule.verbose.exceptions=true' for everything)
********************************************************************************

**Comment by sandipanbasu** [comment]
Hey Alex,

Can you provide the following details --
* what is the Magento version ?
* what is Mule versions ? 
* do you have any connectivity issues with Magento sandbox ?
* which message processor in the connector is throwing this error ? Please provide the payload for more analyses.

**Comment by alex-fernandez** [comment]
Hi @sandipanbasu, how are, I have not heard anything from you for a while. 
- I am using magento_v2_soap.1.7.0.2 and using Mule Version 3.4(for a client).
- I don't have any issues with the sandbox


Suddenly, I have uninstalled the connector and installed the 
    -  Mule Magento Connector Mule Studio Extension	2.0.1.201405131635
and I have not experienced an issue again.
